#!/usr/bin/env bash
# lives at: PointerForce/pointerforce-webui/backend/build/make.sh
# run from: PointerForce/pointerforce-webui/backend/build/
set -euo pipefail

mkdir -p build && cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
make -j"$(nproc)"

BUILD_DIR="$(pwd)"
ROOT_DIR="$(cd "$BUILD_DIR/../.." && pwd)"   # -> PointerForce/

# ---- shared config: keep a single pointerforce.json at PointerForce/config/,
# ---- and point the bridge's expected "config/" (relative to backend/build)
# ---- at it via symlink, instead of duplicating the file.
mkdir -p "$ROOT_DIR/config"
if [ -e "$BUILD_DIR/config" ] && [ ! -L "$BUILD_DIR/config" ]; then
  echo "warning: $BUILD_DIR/config already exists and isn't a symlink \u2014 leaving it alone."
  echo "         move its contents into $ROOT_DIR/config yourself, then rerun make.sh."
else
  ln -sfn "$ROOT_DIR/config" "$BUILD_DIR/config"
fi

# ---- convenience launcher at the PointerForce/ root, so you can run
# ---- ./run_webui instead of cd-ing into backend/build every time.
# ---- (regenerated on every build \u2014 don't hand-edit it.)
cat > "$ROOT_DIR/run_webui" <<EOF
#!/usr/bin/env bash
# auto-generated by make.sh \u2014 re-run make.sh to regenerate.
cd "$BUILD_DIR"
exec ./pointerforce-webui "\$@"
EOF
chmod +x "$ROOT_DIR/run_webui"

echo "built pointerforce-webui"
echo "config: $ROOT_DIR/config/pointerforce.json"
echo "launcher ready: $ROOT_DIR/run_webui"
